version: 2
updates:
  - package-ecosystem: gradle
    directory: /control-plane
    schedule:
      interval: weekly
    groups:
      gradle-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directories:
      - /control-plane
      - /dashboard
      - /build-image
    schedule:
      interval: weekly
