version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 192.168.100.3:5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: https://liftgate.example.com/api/v1/registry/token
    service: 192.168.100.3:5000
    issuer: liftgate
    rootcertbundle: /etc/docker/registry/token.crt
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
