config:
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 5Gi
  cluster:
    enabled: true
    replicas: 3
promExporter:
  enabled: true
podTemplate:
  merge:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
