apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.build.namespace }}
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: privileged
---
{{- with .Values.build.registryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ $.Values.build.namespace }}
  labels:
    {{- include "liftgate.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ . | quote }}
{{- end }}
