apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "liftgate.fullname" . }}-default-deny
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "liftgate.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: control-plane
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "liftgate.fullname" . }}-dashboard
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "liftgate.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dashboard
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "liftgate.fullname" . }}-acme-solver
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
    - Ingress
  ingress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "liftgate.fullname" . }}-prometheus
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              app.kubernetes.io/component: server
      ports:
        - protocol: TCP
          port: 7777
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8081
        - protocol: TCP
          port: 9093
        - protocol: TCP
          port: 9187
{{- if .Values.postgres.managed }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "liftgate.fullname" . }}-postgres
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ include "liftgate.postgresCluster" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: {{ include "liftgate.postgresCluster" . }}
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cloudnative-pg
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8000
{{- end }}
