apiVersion: v1
kind: Secret
metadata:
  name: {{ include "liftgate.fullname" . }}
  labels:
    {{- include "liftgate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.masterKey }}
  LIFTGATE_SECRETS_MASTER_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.github.privateKey }}
  LIFTGATE_GITHUB_APP_PRIVATE_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.github.webhookSecret }}
  LIFTGATE_GITHUB_WEBHOOK_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.github.clientSecret }}
  LIFTGATE_GITHUB_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- if not .Values.postgres.managed }}
  LIFTGATE_DATABASE_USER: {{ .Values.postgres.externalUser | quote }}
  LIFTGATE_DATABASE_PASSWORD: {{ .Values.postgres.externalPassword | quote }}
  {{- end }}
