{{- range $role, $_ := include "liftgate.roles" . | fromJson }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "liftgate.roleName" (list $ $role) }}
  labels:
    {{- include "liftgate.labels" $ | nindent 4 }}
{{- end }}
