import {
  siAngular,
  siAstro,
  siBun,
  siCplusplus,
  siCreatereactapp,
  siDeno,
  siDiscorddotjs,
  siDjango,
  siDocker,
  siDotnet,
  siElixir,
  siExpress,
  siFastapi,
  siFastify,
  siFlask,
  siGin,
  siGleam,
  siGnubash,
  siGo,
  siH3,
  siHono,
  siHtml5,
  siKoa,
  siLaravel,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siNuxt,
  siOpenjdk,
  siPhoenixframework,
  siPhp,
  siPython,
  siReactrouter,
  siRemix,
  siRuby,
  siRubyonrails,
  siRust,
  siSpringboot,
  siSvelte,
  siTanstack,
  siTelegram,
  siVite,
  siVuedotjs,
  type SimpleIcon,
} from "simple-icons";

export const stacks = [
  { id: "next", name: "Next.js", icon: siNextdotjs },
  { id: "nuxt", name: "Nuxt", icon: siNuxt },
  { id: "astro", name: "Astro", icon: siAstro },
  { id: "sveltekit", name: "SvelteKit", icon: siSvelte },
  { id: "vite", name: "Vite", icon: siVite },
  { id: "angular", name: "Angular", icon: siAngular },
  { id: "node", name: "Node.js", icon: siNodedotjs },
  { id: "bun", name: "Bun", icon: siBun },
  { id: "django", name: "Django", icon: siDjango },
  { id: "fastapi", name: "FastAPI", icon: siFastapi },
  { id: "flask", name: "Flask", icon: siFlask },
  { id: "rails", name: "Ruby on Rails", icon: siRubyonrails },
  { id: "laravel", name: "Laravel", icon: siLaravel },
  { id: "go", name: "Go", icon: siGo },
  { id: "rust", name: "Rust", icon: siRust },
];

const icons: Record<string, SimpleIcon> = {
  ...Object.fromEntries(stacks.map((stack) => [stack.id, stack.icon])),
  remix: siRemix,
  "react-router": siReactrouter,
  "tanstack-start": siTanstack,
  "create-react-app": siCreatereactapp,
  vue: siVuedotjs,
  nestjs: siNestjs,
  express: siExpress,
  fastify: siFastify,
  hono: siHono,
  koa: siKoa,
  h3: siH3,
  "discord-js": siDiscorddotjs,
  telegraf: siTelegram,
  php: siPhp,
  gin: siGin,
  "spring-boot": siSpringboot,
  java: siOpenjdk,
  rack: siRuby,
  ruby: siRuby,
  phoenix: siPhoenixframework,
  elixir: siElixir,
  python: siPython,
  fasthtml: siPython,
  deno: siDeno,
  dotnet: siDotnet,
  gleam: siGleam,
  cpp: siCplusplus,
  shell: siGnubash,
  static: siHtml5,
  dockerfile: siDocker,
};

export const stackIcon = (id?: string | null) => (id ? icons[id] : undefined);
