import {
  siAngular,
  siAstro,
  siBun,
  siCplusplus,
  siCreatereactapp,
  siDeno,
  siDiscorddotjs,
  siDjango,
  siDocker,
  siDotnet,
  siElixir,
  siExpress,
  siFastapi,
  siFastify,
  siFlask,
  siGin,
  siGleam,
  siGnubash,
  siGo,
  siH3,
  siHono,
  siHtml5,
  siKoa,
  siLaravel,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siNuxt,
  siOpenjdk,
  siPhoenixframework,
  siPhp,
  siPython,
  siReactrouter,
  siRemix,
  siRuby,
  siRubyonrails,
  siRust,
  siSpringboot,
  siSvelte,
  siTanstack,
  siTelegram,
  siVite,
  siVuedotjs,
  type SimpleIcon,
} from "simple-icons";

export const stacks = [
  { id: "next", name: "Next.js", icon: siNextdotjs },
  { id: "nuxt", name: "Nuxt", icon: siNuxt },
  { id: "astro", name: "Astro", icon: siAstro },
  { id: "sveltekit", name: "SvelteKit", icon: siSvelte },
  { id: "vite", name: "Vite", icon: siVite },
  { id: "angular", name: "Angular", icon: siAngular },
  { id: "node", name: "Node.js", icon: siNodedotjs },
  { id: "bun", name: "Bun", icon: siBun },
  { id: "django", name: "Django", icon: siDjango },
  { id: "fastapi", name: "FastAPI", icon: siFastapi },
  { id: "flask", name: "Flask", icon: siFlask },
  { id: "rails", name: "Ruby on Rails", icon: siRubyonrails },
  { id: "laravel", name: "Laravel", icon: siLaravel },
  { id: "go", name: "Go", icon: siGo },
  { id: "rust", name: "Rust", icon: siRust },
];

const frameworks: Record<string, { name: string; icon: SimpleIcon }> = Object.fromEntries([
  ...stacks.map(({ id, name, icon }) => [id, { name, icon }]),
  ...(
    [
      ["remix", "Remix", siRemix],
      ["react-router", "React Router", siReactrouter],
      ["tanstack-start", "TanStack Start", siTanstack],
      ["create-react-app", "Create React App", siCreatereactapp],
      ["vue", "Vue CLI", siVuedotjs],
      ["nestjs", "NestJS", siNestjs],
      ["express", "Express", siExpress],
      ["fastify", "Fastify", siFastify],
      ["hono", "Hono", siHono],
      ["koa", "Koa", siKoa],
      ["h3", "h3", siH3],
      ["discord-js", "discord.js", siDiscorddotjs],
      ["telegraf", "Telegraf", siTelegram],
      ["php", "PHP", siPhp],
      ["gin", "Gin", siGin],
      ["spring-boot", "Spring Boot", siSpringboot],
      ["java", "Java", siOpenjdk],
      ["rack", "Rack", siRuby],
      ["ruby", "Ruby", siRuby],
      ["phoenix", "Phoenix", siPhoenixframework],
      ["elixir", "Elixir", siElixir],
      ["python", "Python", siPython],
      ["fasthtml", "FastHTML", siPython],
      ["deno", "Deno", siDeno],
      ["dotnet", ".NET", siDotnet],
      ["gleam", "Gleam", siGleam],
      ["cpp", "C++", siCplusplus],
      ["shell", "Shell", siGnubash],
      ["static", "Static site", siHtml5],
      ["dockerfile", "Dockerfile", siDocker],
    ] as const
  ).map(([id, name, icon]) => [id, { name, icon }]),
]);

export const stackIcon = (id?: string | null) => (id ? frameworks[id]?.icon : undefined);

export const stackName = (id?: string | null) => (id ? frameworks[id]?.name : undefined);
